# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='support_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
