# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='dprice',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sprice',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
