# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20171031_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='dprice',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sprice',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=10),
        ),
    ]
